### ISSUE TITLE
Who is instructing?

### ISSUE THREAD

**Issue by pgmccann** [StAResComp/2017-12-04-standrews#2]
@pgmccann and @alex-konovalov? Can we cover Shell, Git, SQL and R between us?

**Comment by olexandr-konovalov** [comment]
IIRC previous discussions, it looks like @widdowquinn for R, @pgmccann for SQL and then some combination of all three of us for Shell and Git. I will invite @widdowquinn to the repository.

**Comment by widdowquinn** [comment]
I'm happy to do R - even happier to share. That's a practical issue as much as anything: a full day for anyone is exhausting! On previous courses we've either scheduled a half-day for R each day, or split a single day across two instructors.

**Comment by olexandr-konovalov** [comment]
I agree. I recommend by all means not make any of us to teach full day!
